#!/usr/bin/env python3
"""
Test the complete frontend-backend audio mapping flow
Validate that audio URLs generated by tool orchestrator reach the frontend properly
"""

import requests
import time
import json

API_BASE = "http://localhost:8001"

def test_complete_audio_mapping():
    """Test the complete audio mapping from tool orchestrator to frontend API"""
    
    print("🧪 Testing Complete Frontend-Backend Audio Mapping...")
    print("=" * 60)
    
    # Create a new session  
    create_response = requests.post(f"{API_BASE}/api/sessions/create", json={
        "user_id": "audio_test",
        "character_id": "seol_min_seok_quiz"
    })
    
    if create_response.status_code != 200:
        print(f"❌ Session creation failed: {create_response.status_code}")
        return False
        
    session_data = create_response.json()
    session_id = session_data.get("data", {}).get("session", {}).get("session_id")
    
    if not session_id:
        print(f"❌ No session_id returned: {session_data}")
        return False
    
    print(f"✅ Session created: {session_id}")
    
    # Test the chatWithSession equivalent (platform-chat -> API client mapping)
    print("\n🎯 Testing chatWithSession flow (platform-chat -> API client)...")
    
    # Step 1: Call platform-chat directly (what API client does internally)
    platform_response = requests.post(f"{API_BASE}/api/platform-chat", json={
        "character_id": "seol_min_seok_quiz",
        "session_id": session_id,
        "user_input": "안녕하세요", 
        "user_id": "audio_test"
    })
    
    if platform_response.status_code == 200:
        platform_data = platform_response.json()
        
        print(f"📋 PLATFORM-CHAT RESPONSE:")
        print(f"   📝 Dialogue: '{platform_data.get('dialogue', '')[:50]}...'")
        print(f"   🎵 Has audio_url field: {platform_data.get('audio_url') is not None}")
        
        if platform_data.get('audio_url'):
            print(f"   📏 Audio URL length: {len(platform_data['audio_url'])}")
            if platform_data['audio_url'].startswith("data:audio/"):
                print(f"   ✅ Audio format: Data URI (correct)")
            else:
                print(f"   ⚠️  Audio format: {platform_data['audio_url'][:50]}...")
        
        # Step 2: Simulate API client mapping (what frontend API client does)
        print(f"\n📡 SIMULATING API CLIENT MAPPING:")
        
        # This is exactly what api-client.ts line 195 does:
        # audio: platformResponse.audio_url || null
        mapped_audio = platform_data.get('audio_url') or None
        
        frontend_response = {
            'character': platform_data.get('character'),
            'dialogue': platform_data.get('dialogue'),
            'emotion': 'neutral',
            'speed': 1.0,
            'audio': mapped_audio,  # <-- The key mapping
            'session_id': platform_data.get('session_id'),
            'tools': platform_data.get('tools', [])
        }
        
        print(f"   🔄 Mapped audio_url to audio: {frontend_response['audio'] is not None}")
        if frontend_response['audio']:
            print(f"   📏 Frontend audio field length: {len(frontend_response['audio'])}")
            print(f"   ✅ Frontend receives proper audio field for AudioPlayer")
        else:
            print(f"   ❌ Frontend audio field is None - AudioPlayer won't work")
        
        print(f"\n🎯 DIAGNOSIS:")
        if platform_data.get('audio_url') and frontend_response.get('audio'):
            print(f"   ✅ Complete audio mapping flow WORKING!")
            print(f"   🎉 Tool Orchestrator → Platform Chat → API Client → Frontend")
            print(f"   💡 Audio should be playing in frontend")
        else:
            print(f"   ❌ Audio mapping flow BROKEN at some step")
            if not platform_data.get('audio_url'):
                print(f"   🚨 Problem: Tool Orchestrator not generating audio_url")
            else:
                print(f"   🚨 Problem: API Client mapping not working properly")
        
        return bool(platform_data.get('audio_url') and frontend_response.get('audio'))
        
    else:
        print(f"❌ Platform-chat request failed: {platform_response.status_code}")
        return False

def main():
    print("🚀 Testing Complete Frontend-Backend Audio Mapping")
    print("=" * 60)
    
    success = test_complete_audio_mapping()
    
    print(f"\n📊 FINAL RESULT:")
    if success:
        print("   ✅ Complete audio mapping flow WORKING!")
        print("   🎉 Audio should reach frontend AudioPlayer component")
        print("   💡 If audio still not playing, check frontend console logs")
    else:
        print("   ❌ Complete audio mapping flow BROKEN")
        print("   🚨 Need to fix audio URL generation or mapping")
    
    return success

if __name__ == "__main__":
    success = main()
    exit(0 if success else 1)